server:
    port: ${SERVER_PORT} 
    ssl:
        enabled: ${SERVER_SSL_ENABLED}
        key-store: ${SERVER_SSL_KEY_STORE}
        key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
        key-store-type: ${SERVER_SSL_KEY_STORE_TYPE}
        key-alias: ${SERVER_SSL_KEY_ALIAS}

spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USER_NAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
    mvc:
        static-path-pattern: /resources/**
    web:
        resources:
            static-locations: file:${IMAGE_SAVE_FILE_PATH}

openai:
    apiKey: ${OPENAI_API_KEY}

image:
    saveFilePath: ${IMAGE_SAVE_FILE_PATH}